# -*- coding: utf-8 -*-
"""สำเนาของ PROGED FINAL PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kgl7d-AHCuG3gnA8lwBH3iMip0JI4I2V
"""

total_semesters = int(input("จำนวนภาคเรียนที่ต้องการคำนวณ : "))
print("-"*60)
semester_count = 1
credit_register_sum = 0
credit_pass_sum = 0
credit_attempt_sum = 0
grade_point_sum = 0
while semester_count <= total_semesters :
  year,semester = [a for a in input(" ปีการศึกษาและภาคเรียน : ").split()]
  total_subject = int(input(" จำนวนรายวิชาที่ต้องการคำนวณ : "))
  subject = 1
  credit_register = 0
  credit_pass = 0
  credit_attempt = 0
  grade_point = 0
  while subject <= total_subject :
    print("-"*40)
    print("  วิชาที่",subject)
    subject_id,subject_credit_input,subject_grade = [a for a in input(" ระบุรหัสวิชา หน่วยกิต และเกรดที่ได้ : ").split()]
    subject_credit = int(subject_credit_input)
    if subject_grade == "A" or subject_grade == "a" or subject_grade == "4" :
      grade = 4
      credit_register += subject_credit
      credit_pass += subject_credit
      credit_attempt += subject_credit
      grade_point += subject_credit*grade
    elif subject_grade == "B+" or subject_grade == "b+" or subject_grade == "3.5" :
      grade = 3.5
      credit_register += subject_credit
      credit_pass += subject_credit
      credit_attempt += subject_credit
      grade_point += subject_credit*grade
    elif subject_grade == "B"or subject_grade == "b" or subject_grade == "3" :
      grade = 3
      credit_register += subject_credit
      credit_pass += subject_credit
      credit_attempt += subject_credit
      grade_point += subject_credit*grade
    elif subject_grade == "C+" or subject_grade == "c+" or subject_grade == "2.5" :
      grade = 2.5
      credit_register += subject_credit
      credit_pass += subject_credit
      credit_attempt += subject_credit
      grade_point += subject_credit*grade
    elif subject_grade == "C" or subject_grade == "c" or subject_grade == "2" :
      grade = 2
      credit_register += subject_credit
      credit_pass += subject_credit
      credit_attempt += subject_credit
      grade_point += subject_credit*grade
    elif subject_grade == "D+" or subject_grade == "d+" or subject_grade == "1.5" :
      grade = 1.5
      credit_register += subject_credit
      credit_pass += subject_credit
      credit_attempt += subject_credit
      grade_point += subject_credit*grade
    elif subject_grade == "D" or subject_grade == "d" or subject_grade == "1" :
      grade = 1
      credit_register += subject_credit
      credit_pass += subject_credit
      credit_attempt += subject_credit
      grade_point += subject_credit*grade
    elif subject_grade == "F" or subject_grade == "f" or subject_grade == "0":
      grade = 0
      credit_register += subject_credit
      credit_attempt += subject_credit
      grade_point += subject_credit*grade
    elif subject_grade == "S" or subject_grade == "s":
      grade = 0
      credit_register += subject_credit
      credit_pass += subject_credit
    else :
      grade = 0
      credit_register += subject_credit
    subject += 1
  gpa = grade_point/credit_attempt
  print("-"*40)
  print(" ข้อมูลผลการเรียนของภาคเรียนที่",semester,"ปีการศึกษา",year)
  print("   │  CR :",credit_register," │  CP :",credit_pass," │  CA :",credit_attempt," │  GP :",grade_point," │  GPA :"+"{:.2f}".format(gpa),"│")
  print("-"*40)
  semester_count += 1
  credit_register_sum += credit_register
  credit_pass_sum += credit_pass
  credit_attempt_sum += credit_attempt
  grade_point_sum += grade_point
  gpax = grade_point_sum/credit_attempt_sum
  print("ข้อมูลผลการเรียนรวมของทุกภาคเรียน")
  print("   │ CRX :",credit_register_sum,"│ CPX :",credit_pass_sum,"│ CAX :",credit_attempt_sum,"│ GPX :",grade_point_sum,"│ GPAX :"+"{:.2f}".format(gpax),"│")
  print("+"*60)
print("หมายเหตุ :")
print("CR หมายถึง หน่วยกิตที่ลงทะเบียน ")
print("CRX หมายถึง หน่วยกิตที่ลงทะเบียนสะสม ")
print("CP หมายถึง หน่วยกิตที่ผ่าน ")
print("CPX หมายถึง หน่วยกิตที่ผ่านสะสม ")
print("CA หมายถึง หน่วยกิตที่นำมาคำนวณ ")
print("CAX หมายถึง หน่วยกิตที่นำมาคำนวณสะสม ")
print("GP หมายถึง คะแนนเกรด ")
print("GPX หมายถึง คะแนนเกรดสะสม ")
print("GPA หมายถึง เกรดเฉลี่ย ")
print("GPAX หมายถึง เกรดเฉลี่ยสะสม ")